export const chatRoomData = [
  {
    roomName: '개발자 모임',
    participantsCount: 3,
    prevMessage: ['1마지막 배포 언제야?', '2오늘 회의 어땠어?'],
    lastMessageTime: '2025-03-28T14:32:00Z',
    unReadCount: 2,
  },
  {
    roomName: '박오스',
    participantsCount: 2,
    prevMessage: ['1번째 최근 채팅', '2번째 최근 채팅'],
    lastMessageTime: '2025-03-28T10:15:00Z',
    unReadCount: 5,
  },
  {
    roomName: '세오스',
    participantsCount: 2,
    prevMessage: ['리액트 훅 정리해봤어', '다음 주 주제는?'],
    lastMessageTime: '2025-03-27T20:44:00Z',
    unReadCount: 0,
  },
  {
    roomName: '이오스',
    participantsCount: 2,
    prevMessage: ['저녁 뭐 먹을래?', '엄마가 오늘 늦으신대'],
    lastMessageTime: '2025-03-27T18:12:00Z',
    unReadCount: 3,
  },
  {
    roomName: '일오스',
    participantsCount: 2,
    prevMessage: ['UI 수정했어요', '프로토타입 확인해주세요'],
    lastMessageTime: '2025-03-27T09:05:00Z',
    unReadCount: 1,
  },
  {
    roomName: '축구팀 단톡',
    participantsCount: 10,
    prevMessage: ['모임 언제 할까?', '다음 경기장 잡았어'],
    lastMessageTime: '2025-03-26T22:48:00Z',
    unReadCount: 0,
  },
  {
    roomName: '졸업준비위원회',
    participantsCount: 7,
    prevMessage: ['단체복 사이즈 입력해줘', '졸업사진 언제 찍지?'],
    lastMessageTime: '2025-03-26T19:30:00Z',
    unReadCount: 4,
  },
  {
    roomName: '여행 가자!',
    participantsCount: 5,
    prevMessage: ['숙소 예약했어', '맛집 리스트 공유함'],
    lastMessageTime: '2025-03-26T13:10:00Z',
    unReadCount: 6,
  },
  {
    roomName: '회사 공지방',
    participantsCount: 20,
    prevMessage: ['3월 근태 마감 안내', '연차 입력 부탁드립니다'],
    lastMessageTime: '2025-03-26T09:00:00Z',
    unReadCount: 0,
  },
  {
    roomName: '동아리방',
    participantsCount: 8,
    prevMessage: ['총회는 언제?', '간식 뭐 사올까?'],
    lastMessageTime: '2025-03-26T08:30:00Z',
    unReadCount: 2,
  },
];
